// Turns the BudouX model (models/th.json) into Rust source at build time.
//
// The runtime therefore contains no JSON parser and does no start-up work: each
// feature group becomes a `phf::Map<&str, i32>` — a perfect hash built here by
// phf_codegen, giving the runtime O(1) lookup with no ordering invariant to
// maintain (unlike the sorted-slice/binary-search table this replaced).
//
// TOTAL is the sum of every weight in the model. BudouX's decision rule is
// `-0.5 * TOTAL + sum(matched weights) > 0`; the runtime rewrites that as
// `2 * sum > TOTAL` to stay in integer arithmetic (TOTAL is odd, so the
// inequality is never a tie).

use std::{env, fs, path::PathBuf};

// Feature groups of a BudouX v0.6 model: unigrams over a 6-character window,
// bigrams and trigrams straddling the candidate boundary.
const FEATURES: [&str; 13] = [
    "UW1", "UW2", "UW3", "UW4", "UW5", "UW6", "BW1", "BW2", "BW3", "TW1", "TW2", "TW3", "TW4",
];

fn main() {
    println!("cargo:rerun-if-changed=models/th.json");
    println!("cargo:rerun-if-changed=build.rs");

    let raw = fs::read_to_string("models/th.json").expect("models/th.json is missing");
    let model: serde_json::Map<String, serde_json::Value> =
        serde_json::from_str(&raw).expect("models/th.json is not a JSON object");

    // A group the runtime does not know about would silently drop out of TOTAL
    // and shift every score, so refuse to build instead.
    assert_eq!(
        model.len(),
        FEATURES.len(),
        "model has {} feature groups, expected {} ({:?})",
        model.len(),
        FEATURES.len(),
        FEATURES
    );

    let mut generated = String::from("// @generated by build.rs from models/th.json — do not edit\n");
    let mut total: i64 = 0;

    for name in FEATURES {
        let group = model
            .get(name)
            .unwrap_or_else(|| panic!("model is missing feature group {name}"))
            .as_object()
            .unwrap_or_else(|| panic!("feature group {name} is not an object"));

        let rows: Vec<(&str, i64)> = group
            .iter()
            .map(|(key, value)| {
                let weight = value
                    .as_i64()
                    .unwrap_or_else(|| panic!("weight for {name}/{key} is not an integer"));
                (key.as_str(), weight)
            })
            .collect();
        total += rows.iter().map(|(_, weight)| weight).sum::<i64>();

        let mut map = phf_codegen::Map::new();
        for (key, weight) in &rows {
            map.entry(*key, weight.to_string());
        }
        generated.push_str(&format!("pub static {name}: &phf::Map<&'static str, i32> = &"));
        generated.push_str(&map.build().to_string());
        generated.push_str(";\n");
    }

    generated.push_str(&format!("pub static TOTAL: i64 = {total};\n"));

    let dest = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR")).join("model.rs");
    fs::write(&dest, generated).expect("failed to write model.rs");
}
