// Turns the BudouX model (models/th.json) into Rust source at build time.
//
// The runtime therefore contains no JSON parser and does no start-up work: each
// feature group becomes a `phf::Map` — a perfect hash built here by phf_codegen,
// giving the runtime O(1) lookup with no ordering invariant to maintain (unlike
// the sorted-slice/binary-search table this replaced).
//
// Keys are *packed integers*, not strings. Every key in a BudouX model is one to
// three characters, so `pack` folds them into a single integer at 21 bits each
// (the width of a Unicode scalar) under a leading sentinel bit that keeps the
// arities from colliding. Unigrams fit a u32; bigrams and trigrams need a u64,
// where three characters plus the sentinel occupy all 64 bits exactly.
//
// That buys two things over `Map<&'static str, i32>`: the binary stops carrying
// 2427 string literals and their fat pointers, and the scoring loop stops
// building a `String` and hashing variable-length bytes for each of its thirteen
// lookups per candidate boundary.
//
// `pack` is duplicated in src/lib.rs — it has to be, since one copy runs at
// build time and the other at runtime. They are kept honest by
// `spot_check_weights_from_the_shipped_model`, which looks up known weights
// through the runtime copy: any disagreement turns every lookup into a miss.
//
// TOTAL is the sum of every weight in the model. BudouX's decision rule is
// `-0.5 * TOTAL + sum(matched weights) > 0`; the runtime rewrites that as
// `2 * sum > TOTAL` to stay in integer arithmetic (TOTAL is odd, so the
// inequality is never a tie).

use std::{env, fmt::Write as _, fs, path::PathBuf};

// Feature groups of a BudouX v0.6 model, with the n-gram width each one indexes:
// unigrams over a 6-character window, bigrams and trigrams straddling the
// candidate boundary.
const FEATURES: [(&str, usize); 13] = [
    ("UW1", 1),
    ("UW2", 1),
    ("UW3", 1),
    ("UW4", 1),
    ("UW5", 1),
    ("UW6", 1),
    ("BW1", 2),
    ("BW2", 2),
    ("BW3", 2),
    ("TW1", 3),
    ("TW2", 3),
    ("TW3", 3),
    ("TW4", 3),
];

/// Fold up to three characters into one integer: a leading 1 bit, then each
/// character in 21 bits, most significant first. The sentinel is what keeps
/// `"ก"` from packing to the same value as `"\0ก"` would.
fn pack(key: &str) -> u64 {
    key.chars().fold(1u64, |acc, c| (acc << 21) | c as u64)
}

fn main() {
    println!("cargo:rerun-if-changed=models/th.json");
    println!("cargo:rerun-if-changed=build.rs");

    let raw = fs::read_to_string("models/th.json").expect("models/th.json is missing");
    let model: serde_json::Map<String, serde_json::Value> =
        serde_json::from_str(&raw).expect("models/th.json is not a JSON object");

    // A group the runtime does not know about would silently drop out of TOTAL
    // and shift every score, so refuse to build instead.
    assert_eq!(
        model.len(),
        FEATURES.len(),
        "model has {} feature groups, expected {} ({:?})",
        model.len(),
        FEATURES.len(),
        FEATURES.map(|(name, _)| name)
    );

    let mut generated = String::from("// @generated by build.rs from models/th.json — do not edit\n");
    let mut total: i64 = 0;

    for (name, width) in FEATURES {
        let group = model
            .get(name)
            .unwrap_or_else(|| panic!("model is missing feature group {name}"))
            .as_object()
            .unwrap_or_else(|| panic!("feature group {name} is not an object"));

        let rows: Vec<(&str, i64)> = group
            .iter()
            .map(|(key, value)| {
                // A *longer* key than the runtime's window would silently lose
                // its leading characters off the top of the u64 and alias onto
                // another entry, so refuse to build. Shorter ones are fine: the
                // shipped model has twelve two-character keys in TW4, left over
                // from training on padded sequences, and the runtime -- which
                // only ever looks up a full three-character window -- can never
                // match them. They stay in TOTAL, exactly as they do in BudouX's
                // reference implementation, which also sums every weight.
                assert!(
                    key.chars().count() <= width,
                    "feature group {name} indexes {width}-character windows, but has key {key:?}"
                );
                let weight = value
                    .as_i64()
                    .unwrap_or_else(|| panic!("weight for {name}/{key} is not an integer"));
                (key.as_str(), weight)
            })
            .collect();
        total += rows.iter().map(|(_, weight)| weight).sum::<i64>();

        // One character plus the sentinel is 22 bits, so unigram groups -- 505 of
        // the model's 2427 entries -- halve their key storage by using a u32.
        let (key_type, table) = if width == 1 {
            let mut map = phf_codegen::Map::<u32>::new();
            for (key, weight) in &rows {
                map.entry(pack(key) as u32, weight.to_string());
            }
            ("u32", map.build().to_string())
        } else {
            let mut map = phf_codegen::Map::<u64>::new();
            for (key, weight) in &rows {
                map.entry(pack(key), weight.to_string());
            }
            ("u64", map.build().to_string())
        };
        writeln!(generated, "pub static {name}: &phf::Map<{key_type}, i32> = &{table};")
            .expect("writing to a String cannot fail");
    }

    writeln!(generated, "pub static TOTAL: i64 = {total};").expect("writing to a String cannot fail");

    let dest = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR")).join("model.rs");
    fs::write(&dest, generated).expect("failed to write model.rs");
}
